global:
  scrape_interval:     10s

  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - '/prometheus/prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    
    scrape_interval: 5s
    
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'system'
    
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          os: 'darwin'

    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.*
        action: drop

  - job_name: 'random-example'
    
    scrape_interval: 5s
    
    static_configs:
      - targets: ['host.docker.internal:40000','host.docker.internal:40001']
        labels:
          group: 'production'

      - targets: ['host.docker.internal:40002']
        labels:
          group: 'canary'
  
  - job_name: 'person-app'
    
    metrics_path: '/actuator/prometheus'
    
    static_configs:
      - targets: ['host.docker.internal:50000']

    metric_relabel_configs:
      - source_labels: [uri]
        regex: (/actuator/prometheus)|(/\*\*/favicon.ico)
        action: drop