groups:
- name: example
  rules:
  - alert: MiddleConcurrency
    expr: avg(rate(rpc_durations_seconds_count[1m])) by (job, service) > 1
    for: 10s
    labels:
      level: waring
    annotations:
      description: concurrency more than 1 millions
  - alert: HighConcurrency
    expr: avg(rate(rpc_durations_seconds_count[1m])) by (job, service) > 5
    for: 10s
    labels:
      level: critical
    annotations:
      description: concurrency more than 5 millions
  - alert: HealthCheck
    expr: sum(up) by (job) < 1
    for: 10s
    labels:
      level: critical
    annotations:
      description: "{{$labels.job}}'s instances are less than 1"
