global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  repeat_interval: 5m
  receiver: 'jzliu'
  routes:
  - receiver: 'jzliu2'
    group_by: ['job']
    match:
      alertname: HealthCheck

inhibit_rules:
  - source_match:
      alertname: 'HighConcurrency'
    target_match:
      alertname: 'MiddleConcurrency'
    equal: ['job', 'service']
  - source_match:
      job: 'system'
      alertname: 'HealthCheck'
    target_match_re:
      alertname: '.*'
