global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'jzliu'
  routes:
  - receiver: 'jzliu2'
    group_by: ['job']
    match:
      alertname: HealthCheck

inhibit_rules:
  - source_match:
      alertname: 'HighConcurrency'
    target_match:
      alertname: 'MiddleConcurrency'
    equal: ['job', 'service']
  - source_match:
      job: 'system'
      alertname: 'HealthCheck'
    target_match_re:
      alertname: '.*'

receivers:
- name: 'jzliu'
  email_configs:
  - to: jzliu@thoughtworks.com
    from: 152390239@qq.com
    smarthost: smtp.qq.com:587
    auth_username: "152390239"
    auth_identity: "mmejvjdwthfkcbdi"
    auth_password: "mmejvjdwthfkcbdi"
- name: 'jzliu2'
  email_configs:
  - to: jkasljz@outlook.com
    from: 152390239@qq.com
    smarthost: smtp.qq.com:587
    auth_username: "152390239"
    auth_identity: "mmejvjdwthfkcbdi"
    auth_password: "mmejvjdwthfkcbdi"
